version: '3.8'

services:
  # SERVICIO DE BASE DE DATOS (MYSQL)
  db:
    image: mysql:8.0
    container_name: tp_final_mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
    restart: unless-stopped 
    ports:
      - "33060:3306"

  # SERVICIO DE BACKEND (FLASK + GUNICORN)
  backend:
    build:
      context: ./backend
    container_name: tp_final_backend
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db 
    working_dir: /app
    ports:
      - "5001:5000"
    restart: unless-stopped
  
  # SERVICIO DE FRONTEND (VUE + NGINX)
  frontend:
    image: node:20-alpine
    env_file:
      - ./frontend/.env.docker
    container_name: tp_final_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - VITE_API_BASE_URL=http://localhost:5001
    ports:
      - "8080:5173"
    depends_on:
      - backend
    restart: unless-stopped
    command: [ "sh", "-c", "npm install && npm run dev -- --host 0.0.0.0" ]

volumes:
  db_data:
  pip_cache_data:
